### ISSUE TITLE
SCSS cleanup

### ISSUE THREAD

**Issue by R4xx4r** [euguilhermegirardi/globo-home-page#3]
First of all - REALLY GOOD WORK! :metal: 
This is just my opinion what I learned the last 2 years as a frontend dev :wink: 
So please dont hate me for this haha

**Try to avoid too much nesting**
I kow its alluring in scss to use the & operator, but believe me for debuging and especially for bugfixing its really annoying.
If you know you have to fix something for example in nav__title you search by typing "nav__title" ... yeaht but if you use it like

```css
nav {
  &__title {
  }
}
```
you will never find your search word :wink: 
So i learned to write some more expressions but have a better fixing live than the other way.
Sometimes like for hover states or something like that i use it too ... So it is not bad and super usefull but for debugging its really unfriendliy .. In my opinion :wink: 

**variables**
In scss you dont need to use the classical var() ... but I think you know that... just wanted to say :wink: 

**cleanup**
you have empty files like _typograph.scss .. I think you will need it or have plans with it, or its just because you needet it a view weeks ago, before you go really live make a small check if all is clean

**mixins**
I like the fact that you are using mixins.
Try to reduce the count and refactor the naming.
If i see 'bp-small-smallest' and `bp-medium-small` I have no idea what this could be.
I allways try to have 3,4 breakpoints like `mobile`, `tablet`, `desktop`, `bigscreen` so i know its also not so clear how much px this is but most of people can think much more about tablet than "medium-small"
By the way - I think this is one of the hardest things about responsiveness haha :laughing: 

Also try to avoid between media queries.
just start mobile first (its just an eample):

```css
.my-responsive-class {
  padding: 0; //mobile

  @media(min-width: 600px) {
    padding: 15px; // tablet
  }

  @media(min-width: 1024px) {
    padding: 15px; // desktop
  }
}
```
so you see i dont need a between :wink: 

also you could avoid something like this:
```css
a {
      @include respond(iphoneX) {
        display: none;
      }

      @include respond(bp-smallest) {
        display: none;
      }

      @include respond(bp-small-smallest) {
        display: none;
      }

      @include respond(bp-medium-small) {
        display: none;
      }

      @include respond(bp-large-medium) {
        display: none;
      }
    }
```
because you set it display none for small and just for bigger ones if you need it ti ... display: block or what ever.

**file structure**
I like how that you are not writing one big file.
there's jsut a small thing :wink: 
For example: why is the slider in layout and not components? So maybe i dont understand it or its just the wrong folder :wink:
